name: 'Sync Version To Terraform'
description: 'Syncs the version of a deployed image to the operations repository'
inputs:
  token-private-repos:
    description: 'Github PAT to access private repos'
    required: true
  service-account-key:
    description: 'Google Cloud Service Account Key'
    required: true
  gcloud-project-id:
    description: 'Google Cloud Project Id'
    required: true
  gcloud-artifact-region:
    description: 'Region for Google Cloud Artifact'
    required: true
  gcloud-artifact-project:
    description: 'Project for Google Cloud Artifact'
    required: true
  gcloud-artifact-repository:
    description: 'Repository for Google Cloud Artifact'
    required: true
  gcloud-artifact-image:
    description: 'Artifact Image name for Google Cloud Artifact'
    required: true
  service-name:
    description: 'Service Name, must match Google Cloud Artifact Service Name'
    required: true
  environment:
    description: 'Environment to update'
    required: true
  file-path:
    description: 'Path to terraform file'
    required: true
  tag:
    description: 'Docker Image tag to sync'
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
      with:
        repository: 'go-fjords/operation'
        ref: 'main'
        token: ${{ inputs.token-private-repos }}
    - uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ inputs.service-account-key }}
        project_id: ${{ inputs.gcloud-project-id }}
        export_default_credentials: true
    - uses: go-fjords/replace-environment-image-digest@v1
      name: Replace Terraform Version
      with:
        image: ${{ inputs.gcloud-artifact-region }}-docker.pkg.dev/${{ inputs.gcloud-artifact-project }}/${{ inputs.gcloud-artifact-repository }}/${{ inputs.gcloud-artifact-image }}
        tag: ${{ inputs.tag }}
        environment: ${{ inputs.environment }}
        path: ${{ inputs.file-path }}
    - uses: EndBug/add-and-commit@v7
      with:
        add: ${{ inputs.file-path }}
        author_name: Tech@GoFjords
        author_email: tech@gofjords.com
        default_author: github_actions
        message: Updated ${{ inputs.environment }} version for ${{ inputs.service-name }} [skip actions]
        push: true